"""Tight v0.1 tolerances selected after the raw 27-scenario measurement.

The uncommitted raw measurement was generated first with both dictionaries
empty.  Thresholds below remain orders of magnitude below errors caused by a
wrong acceleration, timing tick, axis, or sign.
"""

from __future__ import annotations

_EXACT_STATE = {
    "boost": 1.0e-5,
    "jump_time_s": 1.0e-6,
    "air_time_s": 1.0e-6,
    "air_time_since_jump_s": 1.0e-6,
    "flip_time_s": 1.0e-6,
    "flip_rel_torque": 1.0e-6,
}

SAME_EQUATION_TOLERANCES: dict[int, dict[str, float]] = {
    1: {
        "position_uu": 1.0e-5,
        "linear_velocity_uu_per_s": 5.0e-5,
        "orientation_rad": 1.0e-5,
        "angular_velocity_rad_per_s": 1.0e-6,
        "ball_position_uu": 1.0e-5,
        "ball_linear_velocity_uu_per_s": 1.0e-5,
        "ball_orientation_rad": 1.0e-5,
        "ball_angular_velocity_rad_per_s": 1.0e-6,
        **_EXACT_STATE,
    },
    4: {
        "position_uu": 2.0e-5,
        "linear_velocity_uu_per_s": 5.0e-5,
        "orientation_rad": 2.0e-5,
        "angular_velocity_rad_per_s": 2.0e-6,
        "ball_position_uu": 1.0e-5,
        "ball_linear_velocity_uu_per_s": 5.0e-5,
        "ball_orientation_rad": 2.0e-5,
        "ball_angular_velocity_rad_per_s": 1.0e-6,
        **_EXACT_STATE,
    },
    8: {
        "position_uu": 5.0e-5,
        "linear_velocity_uu_per_s": 1.0e-4,
        "orientation_rad": 5.0e-5,
        "angular_velocity_rad_per_s": 3.0e-6,
        "ball_position_uu": 1.0e-5,
        "ball_linear_velocity_uu_per_s": 1.0e-4,
        "ball_orientation_rad": 5.0e-5,
        "ball_angular_velocity_rad_per_s": 1.0e-6,
        **_EXACT_STATE,
    },
    30: {
        "position_uu": 3.0e-4,
        "linear_velocity_uu_per_s": 3.0e-4,
        "orientation_rad": 1.0e-4,
        "angular_velocity_rad_per_s": 5.0e-6,
        "ball_position_uu": 1.0e-5,
        "ball_linear_velocity_uu_per_s": 5.0e-4,
        "ball_orientation_rad": 1.0e-4,
        "ball_angular_velocity_rad_per_s": 1.0e-6,
        **_EXACT_STATE,
    },
    60: {
        "position_uu": 5.0e-4,
        "linear_velocity_uu_per_s": 5.0e-4,
        "orientation_rad": 2.0e-4,
        "angular_velocity_rad_per_s": 1.0e-5,
        "ball_position_uu": 1.0e-5,
        "ball_linear_velocity_uu_per_s": 5.0e-4,
        "ball_orientation_rad": 2.0e-4,
        "ball_angular_velocity_rad_per_s": 1.0e-6,
        **_EXACT_STATE,
    },
    120: {
        "position_uu": 5.0e-4,
        "linear_velocity_uu_per_s": 5.0e-4,
        "orientation_rad": 3.0e-4,
        "angular_velocity_rad_per_s": 1.0e-5,
        "ball_position_uu": 1.0e-5,
        "ball_linear_velocity_uu_per_s": 5.0e-4,
        "ball_orientation_rad": 3.0e-4,
        "ball_angular_velocity_rad_per_s": 1.0e-6,
        **_EXACT_STATE,
    },
}

ROCKETSIM_TOLERANCES: dict[int, dict[str, float]] = {
    1: {
        "position_uu": 2.0e-4,
        "linear_velocity_uu_per_s": 5.0e-4,
        "orientation_rad": 5.0e-4,
        "angular_velocity_rad_per_s": 1.0e-6,
        "ball_position_uu": 5.0e-4,
        "ball_linear_velocity_uu_per_s": 5.0e-4,
        "ball_orientation_rad": 5.0e-4,
        "ball_angular_velocity_rad_per_s": 1.0e-6,
        **_EXACT_STATE,
    },
    4: {
        "position_uu": 3.0e-4,
        "linear_velocity_uu_per_s": 5.0e-4,
        "orientation_rad": 7.0e-4,
        "angular_velocity_rad_per_s": 2.0e-6,
        "ball_position_uu": 5.0e-4,
        "ball_linear_velocity_uu_per_s": 5.0e-4,
        "ball_orientation_rad": 5.0e-4,
        "ball_angular_velocity_rad_per_s": 1.0e-6,
        **_EXACT_STATE,
    },
    8: {
        "position_uu": 3.0e-4,
        "linear_velocity_uu_per_s": 5.0e-4,
        "orientation_rad": 7.0e-4,
        "angular_velocity_rad_per_s": 2.0e-6,
        "ball_position_uu": 5.0e-4,
        "ball_linear_velocity_uu_per_s": 5.0e-4,
        "ball_orientation_rad": 5.0e-4,
        "ball_angular_velocity_rad_per_s": 1.0e-6,
        **_EXACT_STATE,
    },
    30: {
        "position_uu": 7.0e-4,
        "linear_velocity_uu_per_s": 2.0e-3,
        "orientation_rad": 7.0e-4,
        "angular_velocity_rad_per_s": 5.0e-6,
        "ball_position_uu": 1.0e-3,
        "ball_linear_velocity_uu_per_s": 1.0e-3,
        "ball_orientation_rad": 5.0e-4,
        "ball_angular_velocity_rad_per_s": 1.0e-6,
        **_EXACT_STATE,
    },
    60: {
        "position_uu": 2.0e-3,
        "linear_velocity_uu_per_s": 3.0e-3,
        "orientation_rad": 7.0e-4,
        "angular_velocity_rad_per_s": 1.0e-5,
        "ball_position_uu": 2.0e-3,
        "ball_linear_velocity_uu_per_s": 1.0e-3,
        "ball_orientation_rad": 5.0e-4,
        "ball_angular_velocity_rad_per_s": 1.0e-6,
        **_EXACT_STATE,
    },
    120: {
        "position_uu": 3.0e-3,
        "linear_velocity_uu_per_s": 2.0e-3,
        "orientation_rad": 7.0e-4,
        "angular_velocity_rad_per_s": 1.0e-5,
        "ball_position_uu": 3.0e-3,
        "ball_linear_velocity_uu_per_s": 2.0e-3,
        "ball_orientation_rad": 5.0e-4,
        "ball_angular_velocity_rad_per_s": 1.0e-6,
        **_EXACT_STATE,
    },
}
